# Generated by Django 4.2.25 on 2025-10-07 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataSensor',
            fields=[
                ('ID', models.AutoField(db_column='ID', editable=False, primary_key=True, serialize=False)),
                ('temperatura_ambiental', models.FloatField(db_column='temperatura-ambiental')),
                ('humedad_relativa', models.FloatField(db_column='humedad-relativa')),
                ('humedad_suelo', models.FloatField(db_column='humedad-suelo')),
                ('calidad_aire', models.FloatField(db_column='calidad-aire')),
                ('temperatura_agua', models.FloatField(db_column='temperatura-agua')),
                ('fecha_hora', models.DateTimeField(auto_now_add=True, db_column='fecha y hora')),
            ],
            options={
                'verbose_name': 'Dato-Sensor',
                'verbose_name_plural': 'Datos-Sensores',
                'db_table': 'datos-sensores',
            },
        ),
    ]
